# Generated by Django 3.0.2 on 2020-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsAggregator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=1024, verbose_name="Заголовок новости"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        default="", max_length=2048, verbose_name="url новости"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(null=True, verbose_name="Дата новости"),
                ),
            ],
        ),
    ]
